project:
  type: website
  resources:
    - "assets/*"

website:
  title: "tomorrow-lab"
  site-url: https://tomorrow-lab.github.io/
  site-path: "/"
  description: "The future of scientific discovery lies at the convergence of computational power and biological complexity. Our mission is to provide a platform where enthusiasts, researchers, and professionals can learn about and contribute to the rapidly evolving fields of bioinformatics, computational biology, and systems biology."
  favicon: "favicon.ico"
  open-graph: true
  # cookie-consent:
  #   type: implied
  #   style: simple
  #   palette: light
  google-analytics:
    tracking-id: "G-31EWCYNR0V"
    anonymize-ip: true
  # (additional metadata excluded for brevity)
  # body-header: "google_analytics.html"
  # body-footer: Markdown to insert below each page’s body.
  margin-header: subscribe.html
  # margin-footer:
  reader-mode: true
  navbar:
    right:
      - about.qmd
      - projects.qmd
      # - resume.qmd
      - icon: exclamation-triangle
        href: https://partrita.github.io
      - icon: github
        href: https://github.com/partrita
        aria-label: GitHub
      - icon: rss
        href: index.xml
  search:
    location: navbar
    type: overlay #or textbox
  # announcement:
  #   icon: info-circle
  #   dismissable: true
  #   content: "Alert - this is some information that you should pay attention to"
  #   type: info
  #   position: above-navbar
  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
    left: |
      Proudly served by
      [github pages](https://pages.github.com/)

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    css: styles.css
    include-in-header: analytics.html
    toc: true
    number-sections: true
    code-overflow: wrap
    code-tools: false
    code-link: false
    # code-line-numbers: true
    # code-copy: true
    # code-summary: Show Code
    highlight-style: atom-one
    smooth-scroll: true
    link-external-newwindow: true
    anchor-sections: true

    # table and figure setting
    # tbl-cap-location: top
    # fig-cap-location: top
    # fig-align: center
    # fig-responsive: true

    # reference-location: document

    # footnotes-hover: true
    # citation: true
    # citation-location: margin
    # appendix-style: default
    comments:
      giscus:
        repo: partrita/giscus

execute:
  freeze: auto
