project:
  type: website

website:
  title: "tomorrow-lab"
  site-url: https://tomorrow-lab.github.io/
  site-path: "/"
  description: "This is it,,"
  favicon: "favicon.ico"
  open-graph: true
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-31EWCYNR0V"
    anonymize-ip: true
  # (additional metadata excluded for brevity)
  # margin-header: subscribe.html
  # body-header: "google_analytics.html"
  navbar:
    right:
      - about.qmd
      - book.qmd
      - resume.qmd
      - icon: house-up
        href: https://partrita.github.io
      - icon: github
        href: https://github.com/partrita
      - icon: twitter
        href: https://twitter.com/partrita
format:
  html:
    include-in-header: google_analytics.html
    theme:
      light: [theme_light.scss]
      dark: [theme_dark.scss]
    mainfont: Pretendard
    toc: true
    css: styles.css
