project:
  type: website

website:
  title: "Biohacker"
<<<<<<< HEAD
  site-url: https://tomorrow-lab.github.io/
=======
  site-url: https://partrita.github.io/
>>>>>>> 888f799a3b7c3601a0ca44f8713f811b2bff8d2c
  description: "bLog.42"
  favicon: "favicon.ico"
  google-analytics: "GTM-NHHK2BF"
  # (additional metadata excluded for brevity)
  # margin-header: subscribe.html
  # body-header: "google_analytics.html"
  navbar:
    right:
      - about.qmd
      - book.qmd
      - resume.qmd
      - icon: house-up
        href: http://partrita.iptime.org
      - icon: github
        href: https://github.com/partrita
      - icon: twitter
        href: https://twitter.com/partrita
format:
  html:
    theme:
        light: [flatly, custom.scss]
        dark: [darkly, custom.scss]
    css: styles.css



