project:
  type: website

website:
  title: "tomorrow-lab"
  site-url: https://tomorrow-lab.github.io/
  description: "Thi"
  favicon: "favicon.ico"
  google-analytics: "G-31EWCYNR0V"
  # (additional metadata excluded for brevity)
  # margin-header: subscribe.html
  # body-header: "google_analytics.html"
  navbar:
    right:
      - about.qmd
      - book.qmd
      - resume.qmd
      - icon: house-up
        href: http://partrita.iptime.org
      - icon: github
        href: https://github.com/partrita
      - icon: twitter
        href: https://twitter.com/partrita
format:
  html:
    theme:
        light: [litera, custom.scss]
        dark: [darkly, custom.scss]
    css: styles.css



