project:
  type: website

website:
  title: "tomorrow-lab"
  site-url: https://tomorrow-lab.github.io/
  site-path: "/"
  description: "The future of scientific discovery lies at the convergence of computational power and biological complexity. Our mission is to provide a platform where enthusiasts, researchers, and professionals can learn about and contribute to the rapidly evolving fields of bioinformatics, computational biology, and systems biology."
  favicon: "favicon.ico"
  open-graph: true
  cookie-consent:
    type: implied
    style: simple
    palette: light
  google-analytics:
    tracking-id: "G-31EWCYNR0V"
    anonymize-ip: true
  # (additional metadata excluded for brevity)
  margin-header: subscribe.html
  # body-header: "google_analytics.html"
  reader-mode: true
  navbar:
    right:
      - about.qmd
      - book.qmd
      - resume.qmd
      - icon: sign-do-not-enter
        href: https://partrita.github.io
      - icon: github
        href: https://github.com/partrita
      - icon: twitter-x
        href: https://twitter.com/partrita
format:
  html:
    include-in-header: google_analytics.html
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    toc: true
    # css: styles.css
    number-sections: true
