project:
  type: website

website:
  title: "tomorrow-lab"
  site-url: https://tomorrow-lab.github.io/
  description: "Thi"
  favicon: "favicon.ico"
  google-analytics: "G-31EWCYNR0V"
  # (additional metadata excluded for brevity)
  # margin-header: subscribe.html
  # body-header: "google_analytics.html"
  navbar:
    right:
      - about.qmd
      - book.qmd
      - resume.qmd
      - icon: house-up
        href: https://partrita.github.io
      - icon: github
        href: https://github.com/partrita
      - icon: twitter
        href: https://twitter.com/partrita
format:
  html:
    theme:
      light: [theme_light.scss]
      dark: [theme_dark.scss]
    mainfont: Pretendard
    toc: true
    css: styles.css
