[project]
name = "quartoBlog"
version = "0.1.0"
description = "Add a short description here"
authors = ["deepthought <partrita@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
start = "quarto publish gh-pages"
build = "quarto preview"

[dependencies]
python = "==3.9"
quarto = ">=1.4.550,<1.5"
ruff = ">=0.5.5,<0.6"
jupyter = ">=1.1.1,<2"
