[project]
name = "quartoBlog"
version = "0.1.0"
description = "Add a short description here"
authors = ["deepthought <partrita@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]
start = "quarto publish gh-pages"
build = "quarto preview"

[dependencies]
python = "==3.10"
quarto = ">=1.4.550,<1.5"
ruff = ">=0.5.5,<0.6"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.9.1,<4"
pandas = ">=2.2.3,<3"
plotly = ">=5.24.1,<6"
pixi-kernel = ">=0.5.1,<0.6"
ipykernel = ">=6.29.5,<7"
r-irkernel = ">=1.3.2,<2"
