[project]
name = "quartoBlog"
version = "0.1.0"
description = "Add a short description here"
authors = ["deepthought <partrita@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "==3.9"
quarto = "1.3.450.*"
ruff = "0.0.292.*"
